main/PRODUCT/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="PRODUCT"

urlpatterns = [
   path('search/',views.search_p,name='search'),
   path('add_to_cart/',views.add_to_cart,name='add_to_cart'),
  
    # path('products/<slug:pk>',views.all_products,name='detailprod_page'),
   ###############            Cart urls            ##########################
 
    path('add_to_cart/',views.add_to_cart,name='add_to_cart'),
    path('view_cart/',views.view_cart,name='view_cart'),
    path('plus_cart/',views.plus_cart,name='plus_cart'),
   #path('buy_now_checkout/',views.buy_now_checkout,name='buy_now_checkout'),
    path('minus_cart/',views.minus_cart,name='minus_cart'),
    path('delete_cart/',views.remove_cart,name='delete_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('add_tipcoin/',views.add_tipcoin,name='add_tipcoin'),
    path('reduce_tipcoin/',views.reduce_tipcoin,name='reduce_tipcoin'),
    path('add_address/',views.add_address,name='add_address'),
  #################                PAYMENT             #################################
    path('payment_done/',views.payment_done,name="payment_done"),
    #path('success/',views.payment_success,name="payment-success"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/home/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.homepage,name='home'),
    path('user_login/',views.user_login,name='user_login'),
    path('user_signup/',views.user_create_account,name='user_signup'),
    path('user_logout/',views.user_logout,name='user_logout'),
    path('activate_mail/<uid64>/<token>/',views.mail_activation,name='activate_mail'),
    path('dashboard/',views.dashboard,name='dashboard'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/main/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
#from home.sitemap import StaticSitemap
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('PRODUCT.urls')),

#####################   SMTP ###########################

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='password_change/password_reset.html'), name='reset_password'),
    
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_change/password_reset_sent.html'),name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_change/set-password.html'),name='password_reset_confirm'),
    
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_change/password_reset_done.html'),name='password_reset_complete'),

    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/templates/productapp_templates/add_address.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/css/swiper.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Oswald:500" rel="stylesheet">
<script>!function(e){"undefined"==typeof module?this.charming=e:module.exports=e}(function(e,n){"use strict";n=n||{};var t=n.tagName||"span",o=null!=n.classPrefix?n.classPrefix:"char",r=1,a=function(e){for(var n=e.parentNode,a=e.nodeValue,c=a.length,l=-1;++l<c;){var d=document.createElement(t);o&&(d.className=o+r,r++),d.appendChild(document.createTextNode(a[l])),n.insertBefore(d,e)}n.removeChild(e)};return function c(e){for(var n=[].slice.call(e.childNodes),t=n.length,o=-1;++o<t;)c(n[o]);e.nodeType===Node.TEXT_NODE&&a(e)}(e),e});
</script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"></script>


<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Tip Coin</title>
    <style>
         

    </style>
  </head>
  <body >



    <section class="navb" id="home">
        <div class="logo">
           <a href="/">
            <img src="{% static 'img/login/food & beverage.svg' %}" alt="">
           </a>
        </div>
        <a href="{% url 'PRODUCT:view_cart' %}">
          <div class="cart">
            <span>0</span>
            <img src="{% static 'img/add-to-basket.svg'%}" alt="" class="bucket">
           
          </div>
        </a>
        <div class="sidebar" id="bar">
         
            <img src="{% static 'img/menu.png' %}" alt="">
        </div>
        <nav id="navbox">
            <div class="profile">
                <img src="{% static 'img/login/undraw_eating_together_tjhx.svg' %}" alt="">
                <h3>Eat Together</h3>
            </div>
            <div id="crossBox">
                <img src="{% static 'img/close.png' %}" alt="" id="close">
            </div>
            <ul>
                <li><a href="/" class="link"><i class="fa fa-home " aria-hidden="true"></i> Home</a></li>
               
               
                <li><a href="{% url 'dashboard' %}" class="link"><i class="fa fa-address-book-o" aria-hidden="true"></i>Account</a></li>
                <li><a href="{% url 'user_login' %}" class="link"><i class="fa fa-user-o" aria-hidden="true"></i>Login</a></li>
            </ul>
        </nav>
       
    </section>


    </section>

    <main>
        <section class="address">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-12 mx-auto mb-3 ">
                        <div class="card p-5">
                            <h2 class="text-center">Add New Address</h2>
                            <br>
                            <form action="{% url 'PRODUCT:add_address' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                                <div class="form-group">
                                    <label >Full Address:</label>
                                    <input type="text" class="form-control" name='full_address'  placeholder="Enter name" required>
                                  </div>
                                <div class="form-group">
                                  <label >Phone:</label>
                                  <input type="tel" class="form-control"  name='1st_phone' placeholder="Enter Phone" required>
                                </div>

                                  <div class="form-group">
                                    <label >Pincode:</label>
                                    <input type="text" class="form-control"  name='pin' placeholder="Enter Pincode" required>
                                  </div>
                                  <br>
                                <div class="text-center mb-5">
                                    <input type="submit" class="btn btn-info pt-2 pb-2 pl-5 pr-5">
                                </div>
                              </form>
                        </div>

                    </div>

                </div>
            </div>
        </section>

    </main>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Gallery</h2>
                    <br>
                    <div class="d-inline-block">

                       <a href=""> <img src="img/eaters-collective-12eHC6FxPyg-unsplash.jpg" alt="" class="fot-img"></a>
                        <a href=""><img src="img/anna-tukhfatullina-food-photographer-stylist-Mzy-OjtCI70-unsplash.jpg" alt="" class="fot-img"></a>

                    </div>

                    <div class="d-inline-block mt-2">

                       <a href=""> <img src="img/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg" alt="" class="fot-img"></a>
                      <a href="">  <img src="img/casey-lee-awj7sRviVXo-unsplash.jpg" alt="" class="fot-img"></a>

                    </div>
                    <div class="d-inline-block mt-2">

                        <a href=""> <img src="img/pablo-merchan-montes-MXovqM130UI-unsplash.jpg" alt="" class="fot-img"></a>
                       <a href="">  <img src="img/alex-munsell-auIbTAcSH6E-unsplash.jpg" alt="" class="fot-img"></a>

                     </div>
                </div>
                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Links</h2>
                    <br>
                    <div class="p-3 box-top">
                        <ul>
                            <li><a href="index.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Home</a></li>
                            <hr>
                            <li><a href="account.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Account</a></li>
                            <hr>
                            <li><a href="login.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Login</a></li>
                            <hr>

                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Contact Us</h2>
                    <br>
                    <strong class="text-white">Address:</strong>
                    <br>
                    <p class="text-white">Bay Square 1, Building 7, Office 401-23 Business Bay, Dubai, United Arab Emirates</p>
                   <div class="box-top">
                    <hr>
                   </div>
                    <strong class="text-white">Number:</strong>
                    <br>
                    <p class="text-white">+971 44 302 476</p>
                    <div class="box-top">
                        <hr>
                       </div>
                        <strong class="text-white">Email:</strong>
                        <br>
                        <p class="text-white">info@food.com</p>
                </div>
            </div>
        </div>
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>


  <script src="js/index.js"></script>

  </body>
</html>

main/templates/productapp_templates/checkout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/css/swiper.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Oswald:500" rel="stylesheet">
<script>!function(e){"undefined"==typeof module?this.charming=e:module.exports=e}(function(e,n){"use strict";n=n||{};var t=n.tagName||"span",o=null!=n.classPrefix?n.classPrefix:"char",r=1,a=function(e){for(var n=e.parentNode,a=e.nodeValue,c=a.length,l=-1;++l<c;){var d=document.createElement(t);o&&(d.className=o+r,r++),d.appendChild(document.createTextNode(a[l])),n.insertBefore(d,e)}n.removeChild(e)};return function c(e){for(var n=[].slice.call(e.childNodes),t=n.length,o=-1;++o<t;)c(n[o]);e.nodeType===Node.TEXT_NODE&&a(e)}(e),e});
</script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"></script>


<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Tip Coin</title>
    <style>
         

    </style>
  </head>
  <body >



    <section class="navb" id="home">
        <div class="logo">
           <a href="/">
            <img src="{% static 'img/login/food & beverage.svg' %}" alt="">
           </a>
        </div>
        <a href="{% url 'PRODUCT:view_cart' %}">
          <div class="cart">
            <span>0</span>
            <img src="{% static 'img/add-to-basket.svg'%}" alt="" class="bucket">
           
          </div>
        </a>
        <div class="sidebar" id="bar">
         
            <img src="{% static 'img/menu.png' %}" alt="">
        </div>
        <nav id="navbox">
            <div class="profile">
                <img src="{% static 'img/login/undraw_eating_together_tjhx.svg' %}" alt="">
                <h3>Eat Together</h3>
            </div>
            <div id="crossBox">
                <img src="{% static 'img/close.png' %}" alt="" id="close">
            </div>
            <ul>
                <li><a href="/" class="link"><i class="fa fa-home " aria-hidden="true"></i> Home</a></li>
               
               
                <li><a href="{% url 'dashboard' %}" class="link"><i class="fa fa-address-book-o" aria-hidden="true"></i>Account</a></li>
                <li><a href="{% url 'user_login' %}" class="link"><i class="fa fa-user-o" aria-hidden="true"></i>Login</a></li>
            </ul>
        </nav>
       
    </section>
     <main>
        <section class="cart-item">
            <div class="container">
                <br><br>
          <h1>Check Your Cart Items</h1>
                <br>
                <div class="row">
                  {% for i in check_cart %}
                        <td class="d-text">
                         
                        <a href="">
                          <img src="{{i.product_p.image1.url}}" alt="plant/homedecore" class="img-fluid d-img"  height='100' width='100'>  <br>
                        <p></p>
                        </a>
                        </td>
                        <td>{{i.prod_quantity}}</td>
                        <td>₹{{i.product_p.off_price}}</td>
                        <td>₹{{T}}</td>
                        {% endfor %}
                        <td rowspan="2">
                          {{user.first_name}} <br>
                          <br>
                          Total_amount :{{T}}
                          <br>
                          Final_amount:{{total_amount}}
                          {%for i in tip%}
                          <br>
                          {{i.tips_count}}---Tipping 
                          <br>
                          {% endfor %}
                          <br>
                         {{filter_add}} 


                        </td> 
                        </div>

                      </tr>
                      <tr>
                      <br>
                      <br>
                         <form action="{% url 'PRODUCT:payment_done' %}" method="POST">{% csrf_token %}
                          <br>
                          
                          <script src="https://checkout.razorpay.com/v1/checkout.js"
                              data-key="rzp_test_50rfJzBfpU9cKg" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                              data-amount="{{paisa}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                              data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                              data-order_id="{{i.prod_quantity}}"//Replace with the order_id generated by you in the backend. 
                              data-buttontext="Continue With Tip-Coin"
                              data-name="{{user}}"
                              data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
                              data-image="https://example.com/your_logo.jpg"
                              data-prefill.name="Gaurav Kumar"
                              data-prefill.email="gaurav.kumar@example.com"
                              data-theme.color="#F37254">
                          </script>
                          <br>
                          <input type="Hidden" custom="Hidden Element" class="btn btn-success" id="name" name="name"></button></a>
                      
              </from>
<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Gallery</h2>
                    <br>
                    <div class="d-inline-block">
                      
                       <a href=""> <img src="{% static 'img/eaters-collective-12eHC6FxPyg-unsplash.jpg' %}" alt="" class="fot-img"></a>
                       <a href=""><img src="{% static 'img/anna-tukhfatullina-food-photographer-stylist-Mzy-OjtCI70-unsplash.jpg' %}" alt="" class="fot-img"></a>
                       
                    </div>
                    
                    <div class="d-inline-block mt-2">
                      
                       <a href=""> <img src="{% static 'img/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg'%}" alt="" class="fot-img"></a>
                      <a href="">  <img src="{% static 'img/casey-lee-awj7sRviVXo-unsplash.jpg'%}" alt="" class="fot-img"></a>
                       
                    </div>
                    <div class="d-inline-block mt-2">
                      
                        <a href=""> <img src="{% static 'img/pablo-merchan-montes-MXovqM130UI-unsplash.jpg' %}" alt="" class="fot-img"></a>
                       <a href="">  <img src="{% static 'img/alex-munsell-auIbTAcSH6E-unsplash.jpg' %}" alt="" class="fot-img"></a>
                        
                     </div>
                </div>
                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Links</h2>
                    <br>
                    <div class="p-3 box-top">
                        <ul>
                            <li><a href="index.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Home</a></li>
                            <hr>
                            <li><a href="account.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Account</a></li>
                            <hr>
                            <li><a href="login.html"><i class="fa fa-check-square-o pr-2" aria-hidden="true"></i>Login</a></li>
                            <hr>
                           
                        </ul>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6 col-12 mx-auto mb-3">
                    <h2 class="text-white">Contact Us</h2>
                    <br>
                    <strong class="text-white">Address:</strong>
                    <br>
                    <p class="text-white">Bay Square 1, Building 7, Office 401-23 Business Bay, Dubai, United Arab Emirates</p>
                   <div class="box-top">
                    <hr>
                   </div>
                    <strong class="text-white">Number:</strong>
                    <br>
                    <p class="text-white">+9593879456</p>
                    <div class="box-top">
                        <hr>
                       </div>
                        <strong class="text-white">Email:</strong>
                        <br>
                        <p class="text-white">7saikat7@gmail.com</p>
                </div>
            </div>
        </div>
    </footer>
    
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

   
  <script src="{% static 'js/index.js' %}"></script>
  
  </body>
</html>